### ISSUE TITLE
Component error: bring_shopping_list - Integration 'bring_shopping_list' not found.

### ISSUE THREAD

**Issue by msanchezt** [dotKrad/hass_bring_shopping_list_component#4]
Starting on version 2021.6 the component can't be found (error while checking configuration).

I suspect this is because the version on manifest.json file is missing.

**Comment by dotKrad** [comment]
manifest updated, this component will be entering in a not maintained stage, there are better ones out there :)

**Comment by NoxNoctium** [comment]
After updating this error is logged:
`ERROR (MainThread) [custom_components.hacs] <Integration dotKrad/hass_bring_shopping_list_component> Could not read manifest.json [Expecting property name enclosed in double quotes: line 10 column 3 (char 237)]`


> there are better ones out there :)

Can you elaborate on that? The only working alternative I can find is: https://github.com/vlebourl/shopping_list

**Comment by NoxNoctium** [comment]
works with the latest commit `bbde3bf`, thanks!
